### ISSUE TITLE
Dock shows when mousing over any part of screen edge (not just dock area)

### ISSUE THREAD

**Issue by krunaldodiya** [pop-os/cosmic-dock#114]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
Dock keep showing even if mouse is not over

**Steps to reproduce (if you know):**
Enable dock, disable extends to the edges and now move the mouse anywhere at bottom but NOT on dock, it will still show the Dock which is annoying

**Expected behavior:**
Dock should only appear once mouse is over on the visible part of dock

**Other Notes:**

**Comment by jacobgkau** [comment]
Since the user can't see how wide the dock is unless it's shown, only showing when the mouse is over the dock-occupied space might introduce more inconsistency than we'd like.

**Comment by krunaldodiya** [comment]
> Since the user can't see how wide the dock is unless it's shown, only showing when the mouse is over the dock-occupied space might introduce more inconsistency than we'd like.

That's true, is there any key binding to toggle Dock ?

**Comment by leviport** [comment]
>is there any key binding to toggle Dock?

I don't believe so, and I don't think such a key binding would make a lot of sense for that. The dock is primarily a mouse-oriented set of controls. If a user is already using the keyboard, the app library and the launcher are much easier to interact with via keyboard.
