### ISSUE TITLE
Workspaces, Launcher, and Applications buttons do not work in the dock under v22.04

### ISSUE THREAD

**Issue by wagnerck** [pop-os/cosmic-dock#122]
The Show Launcher, Show Workspaces, and Show Applications buttons in the COSMIC dock do not work in the current v22.04 version (`gnome-shell-extension-cosmic-dock` package version `70~ubuntu1pop0~1641401554~21.10~4c62ba4`). Clicking on them does nothing at all.

Possibly related output in syslog:

```
Mar 25 10:41:27 pop-os systemd[2073]: message repeated 2 times: [ Started Application launched by gnome-shell.]
Mar 25 10:41:29 pop-os systemd[2073]: app-gnome-pop\x2dcosmic\x2dworkspaces-3587.scope: Couldn't move process 3587 to requested cgroup '/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-pop\x2dcosmic\x2dworkspaces-3587.scope': No such process
Mar 25 10:41:29 pop-os systemd[2073]: app-gnome-pop\x2dcosmic\x2dworkspaces-3587.scope: Failed to add PIDs to scope's control group: No such process
Mar 25 10:41:29 pop-os systemd[2073]: app-gnome-pop\x2dcosmic\x2dworkspaces-3587.scope: Failed with result 'resources'.
Mar 25 10:41:29 pop-os systemd[2073]: Failed to start Application launched by gnome-shell.
```

The default GNOME "Workspaces" and "Applications" links in the top bar work normally. The launcher works normally when pressing the Super key; configuring Super to launch Workspaces or Applications works as well.

**Comment by jackpot51** [comment]
Fixed in https://github.com/pop-os/cosmic/commit/913b92ce90fdd8db29ab8e0798074f4fc5ba5415
