### ISSUE TITLE
[22.04] Dock fix for USB crashing Nautilus breaks fully extended dock justification.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-dock#127]
With `9c6c88b`, the Dock is now justified to the start point for the set language when extended to the edges (that is left-justified in left-to-right languages like English, right-justified in right-to-left like Arabic). The dock is also top-justified in all languages.

Bottom Behaviour:
![Screenshot from 2022-03-30 11-49-09](https://user-images.githubusercontent.com/98765732/160901553-bdfea8b8-f58b-4c93-84e2-51ededc57ba9.png)
 
 
 Side Behaviour:
![Screenshot from 2022-03-30 12-55-35](https://user-images.githubusercontent.com/98765732/160910216-b4c7f6ba-573d-4726-99cc-685cabde6648.png)

**Comment by jackpot51** [comment]
Fixed in d3a5f81
