### ISSUE TITLE
Please, contribute back upstream

### ISSUE THREAD

**Issue by 3v1n0** [pop-os/cosmic-dock#139]
Hey, I've been looking at latest commits of this project, and I think that some of the commits or features I see here could be easily integrated in the upstream dash2dock project too, for example:
 - https://github.com/pop-os/cosmic-dock/commit/8f33b3bbb44c98e30b205a01f6dffe7741996b9c (dock hiding menu fix)
 - https://github.com/pop-os/cosmic-dock/commit/6b49c08f7ab11b545751b631d9025a40d4d52107 (manual hide)
 - https://github.com/pop-os/cosmic-dock/commit/0e9e03d7726e2dcd276faf88978494011a5b58af https://github.com/pop-os/cosmic-dock/pull/135 (random fixes)
 - https://github.com/pop-os/cosmic-dock/pull/128
 - https://github.com/pop-os/cosmic-dock/commit/d3a5f811fa7fd9d6f111e8fd91b47b79f679396b (center-aligned icons: adding a setting for this)

Given that this is a quite popular extension and that the people actually working on it are just a few, it would be very appreciated if we could join the efforts as much as we can, keeping our forks for the distro-specific things, but trying to unify the code base the most we can.

**Comment by jackpot51** [comment]
Yes, I. interested in pushing these changes upstream

**Comment by 3v1n0** [comment]
Cool, I'm happy to review them then :)

**Comment by jackpot51** [comment]
@13r0ck could you take a look into this?

**Comment by 13r0ck** [comment]
Can do!

**Comment by 13r0ck** [comment]
PR created [here](https://github.com/micheleg/dash-to-dock/pull/1732)

**Comment by 13r0ck** [comment]
https://github.com/micheleg/dash-to-dock/pull/1732 ~~changes have been upstream-ed. Waiting to be merged as of writing this.~~

edit: [7/7/22] upstream PR has been merged
