### ISSUE TITLE
Auto-hidden dock does not always appear when bringing the mouse cursor to the bottom of the screen.

### ISSUE THREAD

**Issue by notnullnotvoid** [pop-os/cosmic-dock#162]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

When the dock is hidden and I bring the mouse to the bottom of the screen, it is inconsistent whether the dock appears or not. It seems to depend somewhat on the vertical speed of the mouse, with fast movement usually causing it to show, and slow movement not causing it to show, but the threshold does seems very inconsistent. It also seems to be very unlikely to show up if the mouse hits the bottom edge of the screen at a relatively shallow angle, below around 30 degrees or so, even if it's moving quickly.

**Steps to reproduce (if you know):**

Set the dock to "Always hide" and move the mouse cursor slowly to the bottom edge of the screen.

**Expected behavior:**

The dock should always appear when I bring the cursor to the bottom of the screen, as in other operating systems.

**Other Notes:**

It's possible that this is some kind of intentionally programmed behavior, but if so it is still a bug, as realistically nobody would want or expect it to work this way, the behavior is not consistent or predictable, feels unresponsive and is bad for usability.

**Comment by n3m0-22** [comment]
I can confirm this, although you do have to move the cursor very slow for it to happen. This may be intentional to prevent the dock from popping up with a slight brush against the mouse.


https://user-images.githubusercontent.com/11048214/178168663-7c269af9-fa5c-4dd5-9eb0-c31731e59ef6.mp4

**Comment by notnullnotvoid** [comment]
I should say, this especially tends to bother me when my mouse is already near the bottom right/left side of the screen, as it 1. won't have much velocity by the time it hits the bottom edge and 2. will hit at a shallow angle since I'm moving it from the side of the screen toward the center (where I know the dock is going to be).

**Comment by leviport** [comment]
I wonder if tweaking `/org/gnome/shell/extensions/dash-to-dock/pressure-threshold` in dconf-editor changes the behavior

**Comment by n3m0-22** [comment]
Yes that does seem to resolve it. Just as an example the default is 100 if I set it to 1 even the slowest movement of the cursor I can manage brings up the dock. @notnullnotvoid I think somewhere around 30 will work for you. You can experiment with the exact value.

Enter this command in the terminal and adjust the value to to suit your needs.

`gsettings set org.gnome.shell.extensions.dash-to-dock pressure-threshold 30`

**Comment by n3m0-22** [comment]
@notnullnotvoid I'm closing this issues. If you are still having problems, and the above command does not resolve it for you I can always reopen.

**Comment by notnullnotvoid** [comment]
That workaround does get rid of the issue, but it's rather sad to see this closed as wontfix. PopOS has the potential to be a good operating system, but an unwillingness to get the details right for things like this holds it back.

**Comment by leviport** [comment]
It's a default gsetting, and one that most people don't have a problem with. Saying that this single gsetting is holding Pop!\_OS back is rather hyperbolic. Still, if you think the default setting absolutely must be changed, then we'd love to test your pull request.

**Comment by notnullnotvoid** [comment]
This and several other major issues I ran into within a couple hours of booting PopOS. I submitted issues for a few of them before running out of patience. Eventually I gave up and went back to win10. I don't particularly feel like submitting a pull request (which will inevitably be rejected) for an operating system I am no longer using, but needless to say there are fairly obvious reasons why other operating systems don't do this.

**Comment by leviport** [comment]
> I don't particularly feel like submitting a pull request

No worries

> (which will inevitably be rejected) 

Nonsense

Sorry Pop wasn't a good fit for you, and I'm glad to hear Windows 10 is suiting your needs better. Thank you for giving Pop a try anyway. I'm going to lock this thread now.
