### ISSUE TITLE
Dock slightly visible when it should not be

### ISSUE THREAD

**Issue by pbauerochse** [pop-os/cosmic-dock#176]
Hi,

I have a dual monitor setup: my laptop display is the primary display and my desktop monitor is the secondary display. I'm showing the dock on both displays but I have it set to hide, when there are overlapping windows. I noticed, that on the primary display the dock icons can be slightly seen (even on the lock screen once logged in) and also when there is an overlapping window on the primary screen (see Screenshot). On the secondary screen everything works as expected: the dock is completely invisible when there are overlapping windows and only shows up, when the mouse gets close.

![image](https://user-images.githubusercontent.com/1038095/203953312-1bebdd20-e8de-43c1-a337-54299fb8aca3.png)

**Comment by psychoticnmina** [comment]
> Hi,
> 
> I have a dual monitor setup: my laptop display is the primary display and my desktop monitor is the secondary display. I'm showing the dock on both displays but I have it set to hide, when there are overlapping windows. I noticed, that on the primary display the dock icons can be slightly seen (even on the lock screen once logged in) and also when there is an overlapping window on the primary screen (see Screenshot). On the secondary screen everything works as expected: the dock is completely invisible when there are overlapping windows and only shows up, when the mouse gets close.
> 
> ![image](https://user-images.githubusercontent.com/1038095/203953312-1bebdd20-e8de-43c1-a337-54299fb8aca3.png)
> 

Are you using any special themes?

**Comment by pbauerochse** [comment]
Nope, only the dark Pop!Os Theme without further customizations.

![image](https://user-images.githubusercontent.com/1038095/204734467-f6d3e1ae-9da8-42cc-98d8-07010b1e54dd.png)

**Comment by psychoticnmina** [comment]
Can I see a video of you performing this so I can try to find the error.

**Comment by pbauerochse** [comment]
Hi @CatPerson136 , I feel stupid. I just noticed, that the image seems to be burnt into the screen. I didn't think of this as this is a quite new laptop. I only have it since August. I started from a pop!OS USB stick and even there the dock is slightly visible. I'll close this issue. Thanks for your help anyways
