### ISSUE TITLE
[FEATURE REQUEST] Isolate programs on Dock, based upon the monitor/workspace the program is opened

### ISSUE THREAD

**Issue by asingh-d12** [pop-os/cosmic-dock#27]
Hi Pop-OS team,

Is it possible to add something like this to the dock, where programs running on a particular monitor/workspace show on that monitor/workspace.

Thanks.
Amrit

**Comment by NathanaelA** [comment]
@asingh-d12 - as I was fixing my dock to do what I wanted today, it appears there is a setting for this in there.     You can use `dconf-editor` and then navigate to 'org.gnome.shell.extensions.dash-to-dock' and then you can see all the settings that the POP-OS team forgot to expose in their new settings page....     I think you would either need "multi-monitor" dock turned on and isolate-monitor and isolate-workspaces, or perhaps just isolate-workspaces if all you are wanting to do is isolate it for just each workspace.

**Comment by asingh-d12** [comment]
Thanks @NathanaelA 
That helps a lot, didn't know so much was missing (and maybe yet to come) from dock options.

I was able to find the options to what I wanted.
