### ISSUE TITLE
Align icons within extended dock

### ISSUE THREAD

**Issue by IamJeffG** [pop-os/cosmic-dock#34]
This is a request for a setting/option to align the icons within the Dock, when the dock is extended to edges of the screen.

| COSMIC Dock | dash-to-dock |
|-------------|--------------|
|  ![Screenshot from 2021-07-07 10-03-04](https://user-images.githubusercontent.com/2002703/124783882-05362180-df0b-11eb-85bf-7f8585a5ff71.png)  |  ![Screenshot from 2021-07-07 10-00-09](https://user-images.githubusercontent.com/2002703/124783539-c4d6a380-df0a-11eb-9063-3892427d9781.png)  |

Specifically, I lock the dock to the left edge of the screen, and I want the icons to be top-aligned.  Basically the same way that dash-to-dock does it in the screenshot above.

Motivation behind this request: I find it very convenient for muscle memory to have the same "favorites" icons always at the exact same position on the screen.  When top-aligned they always stay the same distance from the top of the screen.  But with COSMIC Dock's middle-alignment, their position from top-of-screen changes depending on how many total icons are on the dock right now.

**Comment by patrickfv** [comment]
I have a fork of this extension that does exactly that but by default whenever the dock is vertical, my doubt is whether it's worth implementing an option to enable this as it makes more sense at the top than centered.
