### ISSUE TITLE
How to enable Cosmic-dock after giving the option initially to show no dock

### ISSUE THREAD

**Issue by alexcpn** [pop-os/cosmic-dock#42]
Hi, After the initial upgrade to PoP OS 21 , I gave the option to not show the dock. How do I reconfigure it back; so that I get the similar behaviour like Pop OS 20; Superkey shows the dock on the left side. I am not getting which file has the settings for this '/usr/share/gnome-shell/extensions/cosmic-dock@system76.com'

**Comment by adil192** [comment]
You've likely figured this out already but it's just in the Settings app > Desktop > Dock > Dock Visibility

**Comment by alexcpn** [comment]
Thanks for the reply; Its not about the position of the Dock, but in earlier version with the Superkey press, the dock used to be visible (now I need to press Superkey + A for all Apps , but not the ones I configured in the Dock). So with the keyboard itself I could select the apps with minimum usage of mouse. Seems it is not possible now

**Comment by leviport** [comment]
The dock now appears in the Workspaces overview (Super + D, or clicking "Workspaces" in the top left), not the Applications overview. It is also possible to configure the dock to either "always hide" or "intelligently hide". For both, pushing your mouse cursor against the edge of the screen your dock is on will make the dock appear. This is indeed a bit different from 20.04, but it was designed with careful consideration for mouse-only workflows.

**Comment by alexcpn** [comment]
Thanks ; I am used to the current shortcuts now; it seemed pretty different a few months back; Now its fine for me
