### ISSUE TITLE
Adjust the default icon click action to be an option in the Dock settings.

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-dock#54]
The change to minimize windows on clicking an app icon in the dock resulted in the frustration among the users. Improving the default behavior would take more research and improvements, especially when it comes to showing window previews for multiple windows of the same application. So the suggestion is to make the minimize behavior optional for now and expose the setting in GCC. The quick mockup is included. That would not allow people to have previews but this behavior doesn't seem to be working well at the moment. 
![settings-dock-icon-click](https://user-images.githubusercontent.com/57502897/129603572-ba7ec305-f6b2-4ae1-a8c7-3770c1d2f789.png)

**Comment by jacobgkau** [comment]
Just a heads-up, looking at the options available in the gschema: https://github.com/pop-os/cosmic-dock/blob/73c63baaf1141191bf4d7429575c1fb45fa781f8/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml#L3 

I don't see a current option that would allow for `Launch or Minimize Windows` without a preview. The only options including minimize are `minimize-or-overview` (which just opens Workspaces), `minimize-or-previews` (the current option), or `focus-minimize-or-previews` (which may be worth trying out.)

It sounds like what you're wanting would be a new `minimize-or-cycle` option that would need to be implemented? Or would `Launch or Minimize Windows` in the mockup be the current `minimize-or-previews` option?

**Comment by maria-komarova** [comment]
We are looking at `minimize` instead of `minimize-or-previews` option for now - for the Launch or Minimize Windows option.

**Comment by maria-komarova** [comment]
In terms of previews we still want to do some mockups and usability testing before we figure out what the design should be exactly. There are some usability questions to work through there.

**Comment by jacobgkau** [comment]
For the record, I thought the previews as implemented were far more useful than cycling. Cycling gets less convenient the more windows that are open, and I often end up with a large number of windows open across various workspaces. (Clicking through ten different windows and being bounced between several workspaces in the process, raising various windows that I don't need while looking for the correct one, is not as easy as being able to pick the one that I need using the previews.)

**Comment by maria-komarova** [comment]
Thanks for the information. I'm not saying they couldn't be useful, only that current implementation needs some improvement. And that it would be helpful to better understand people's needs regarding it. So it is great to learn about your use case.

**Comment by PapayaMedia** [comment]
I also like the new behavior more than the previous one. Actually, in my case, I feel the previous one absolutely tedious.

And I’d want to insist in the possibility to implement Plank’s mouse wheel up and down behavior over a dock icon. It does exactly the previous click behavior, but you can go backwards too.

So, if everything is configurable. I’d set my system to minimize/restore on click, and cycle through same app windows scrolling up and down with the mouse wheel.

**Comment by PapayaMedia** [comment]
I'd also like to point that the window switcher is using Pop!_OS close button, but for consistency, I suggest to use GTK close button instead. So, in the following screenshot, it should be just a red circle:

![Window switcher screenshot](https://i.ibb.co/p2TwSMx/Screenshot-from-2021-08-17-08-24-17.png)
