### ISSUE TITLE
MAKE DOES NOT WORK

### ISSUE THREAD

**Issue by ckosedag** [pop-os/cosmic-dock#6]
msgfmt -c po/ar.po -o po/ar.mo
make: msgfmt: No such file or directory
make: *** [Makefile:54: po/ar.mo] Error 127

How Can I solve?

**Comment by ghost** [comment]
same here

**Comment by jacobgkau** [comment]
```
 make: msgfmt: No such file or directory
```
Your system is missing the `msgfmt` command, which means the `gettext` package is missing. Install it with `sudo apt install gettext`, or install all of the build dependencies with `sudo apt build-dep gnome-shell-extension-cosmic-dock`.

I have removed `gettext` on my system and confirmed that installing build deps re-installs it, so I'm closing this issue.
