### ISSUE TITLE
Gap between the dock and edge is missing (or not as visibile)

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-dock#63]
![image](https://user-images.githubusercontent.com/3430283/133808266-5578307e-7154-46a8-9f1f-dd46ad7f9d2a.png)

**Comment by jackpot51** [comment]
The margins are not really correct compared to 21.04. I think @isantop should see about re-theming this, since the previous CSS modifications had to be dropped because upstream refactored styling.

**Comment by jackpot51** [comment]
I think this was fixed in #65
