### ISSUE TITLE
[Feature Request] Add notification badge to respective apps on dock

### ISSUE THREAD

**Issue by NikhilJoshua** [pop-os/cosmic-dock#64]
## Feature Request: Notification Badge
- Adding notification badge will improve the UX
- Makes dock even more productive

## Example Screen Shots
- Windows Task bar has it but couldn't find a CC Screenshot.
- This is a mobile's screen but it gets the idea.

![image](https://user-images.githubusercontent.com/8474784/135058022-cc1ddec0-3976-4b67-b206-2c8fb3b7edb3.png)

**Comment by leviport** [comment]
This seems to work for some apps, so it might be a per-app kind of issue. Which apps were you noticing it not working on?
![2021-09-28_08-56](https://user-images.githubusercontent.com/13512097/135112465-e39e0577-b957-4c05-97f1-c71775cf0c5a.png)

**Comment by NikhilJoshua** [comment]
@leviport It's not working on Slack Client in my system. I removed Pop Shop from the dock after installation so didn't know it existed.

**Comment by leviport** [comment]
Thanks for the info!

**Comment by isantop** [comment]
Just want to confirm that adding notification badges does depend on the apps themselves implementing it; the API is available however.

**Comment by NikhilJoshua** [comment]
@isantop so is it the problem with slack? As far as I know they implemented that feature on Windows and Mac.

**Comment by isantop** [comment]
That's correct. The APIs which Windows uses are different from the ones Mac uses, which in turn are both different from the Linux API. Slack will need to implement this for their Linux build in order for a notification badge to show.

**Comment by NikhilJoshua** [comment]
Okay, will report it to slack team. Thanks for the info. :)

**Comment by robinwkurtz** [comment]
@NikhilJoshua did you get any feedback on this from Slack?
