### ISSUE TITLE
21.10: Window counter dots look bad when many instances of an app are open

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-dock#67]
Looks like 21.04 stops adding dots after 4 windows, so that could be a solution.
![Screenshot from 2021-10-07 10-52-35](https://user-images.githubusercontent.com/13512097/136430197-e21bb4c2-a2e0-4290-a1c3-f98258bd1b4d.png)

**Comment by 13r0ck** [comment]
Should be closed because of #78

**Comment by leviport** [comment]
Feel free to close issues if you think they should be closed.
