### ISSUE TITLE
Minimize from dock icon

### ISSUE THREAD

**Issue by apicgg** [pop-os/cosmic-dock#7]
The dock works great with pop os. But users should be able to minimize the opened windows from the dock icons by clicking on the icons just like in windows. Guess it adds more functionality to the users users.

**Comment by nourkagha** [comment]
You can do this by editing the dconf, using Dconf Editor (GUI dconf editor), or by simply typing this command in the terminal:

```
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize-or-previews' 
```

I agree it should be the default behaviour though, in addition to an adjustable option for it in the Dock settings.

**Comment by apicgg** [comment]
Thanks for your help.
