### ISSUE TITLE
The application dock becomes vertical in some cases.

### ISSUE THREAD

**Issue by aditya369007** [pop-os/cosmic-dock#71]
Please refer to the attached image.
![image](https://user-images.githubusercontent.com/29108722/138241636-889928f2-8994-43db-8729-d00b4d3ff494.png)

Steps to reproduce:
When I disconnect an external monitor, the dock goes from horizontal as intended below, to as shown in the image.

Please do let me know if you need more information.
Thank you for developing Pop-OS.

**Comment by leviport** [comment]
Are you currently on the 21.10 beta? This sounds like the issue reported here: https://github.com/pop-os/beta/issues/227

**Comment by aditya369007** [comment]
Yes I am on beta, so sorry for breaking the norm. I didn't know there was a beta channel. I thought it as it was a dock issue hence I posted it here.

**Comment by leviport** [comment]
No worries, thanks for helping test the beta!
