### ISSUE TITLE
Dock Intelli-hide > Make the dock hide when any unfocused window covers it

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-dock#8]
The current behavior is inconsistent. If two windows of the same applications are open and the unfocused window is covering the dock, the dock will hide. If two windows of different apps are open with one covering the dock, the dock will cover the unfocused app.

This is particularly bad on desktop monitors and with auto-tiling. It looks bad and content get covered by the dock.

**Comment by ids1024** [comment]
So we want intellihide to be based on any window instead of just the focused one?

It seems dash-to-dock has an option for `intellihide-mode` that should allow that.
