### ISSUE TITLE
No Cosmic Dock on fresh POP OS install

### ISSUE THREAD

**Issue by Deathwatch85** [pop-os/cosmic-dock#88]
Hello!
I'm currently trying out Pop OS 21.04 and after a fresh install, I realized that there was no dock. So I went on Github and tried to install everything. Upon using the apt to install it I get "Unable to locate package gnome-shell-extension-cosmic-dock" and if I try to install from git the makefile also doesn't work. Gnome tweak tools were also not preinstalled and showing in my settings. Is there any way to fix that? Thanks

![Bildschirmfoto 2021-11-27 um 01 07 24](https://user-images.githubusercontent.com/4163005/143661965-f26e80b0-7711-4d19-a6fe-6fec2192d0cf.png)

**Comment by leviport** [comment]
Hmm, 21.04 clean installs should have cosmic-dock by default. Can you run these two commands and share the output?
```
sudo apt update
apt policy gnome-shell-extension-cosmic-dock
```

**Comment by Deathwatch85** [comment]
I was kinda confused by it not being there as well. Gnome Tweak Tools wasn't installed as well. I had to install it myself and even then settings for cosmic dock didn't show up. So I now tried both commands again and this was the output
![Bildschirmfoto 2021-11-29 um 22 55 56](https://user-images.githubusercontent.com/4163005/143949621-99d231af-7c83-4b5d-b377-18e45f422429.png)
.

**Comment by leviport** [comment]
I see, you're on Focal (20.04), not Hirsute (21.04). Cosmic-dock wasn't really intended for usage on 20.04. If you want a dock on 20.04, I'd recommend using the dash-to-dock extension, which is what cosmic-dock is based off of.
