### ISSUE TITLE
Please re-add a border to the dock

### ISSUE THREAD

**Issue by ghost** [pop-os/cosmic-dock#95]
In Pop!_OS 21.10 the dock no longer has a border around it and it looks kinda weird without it. Please consider re-adding it.

Thanks

**Comment by leviport** [comment]
Thanks for the feedback! The current styling matches the intended design, so unfortunately we won't be adding the border back until the design changes. If you want to customize your install, you may find more options by substituting the dash-to-dock extension instead of cosmic-dock.
