### ISSUE TITLE
Disproportionate Dock in HD Resolution

### ISSUE THREAD

**Issue by rckmachado** [pop-os/cosmic-dock#99]
The dock is totally out of proportion in HD resolution.

[Print](https://www.notion.so/rickmachado/Dock-Pop-_OS-21-10-2788335f2b4543f28520e7c0662130f5)

**Comment by leviport** [comment]
Thanks for the report! I believe the issue is the applications library not scaling elegantly to smaller resolutions, not that the dock is sized incorrectly. Closing as a duplicate of https://github.com/pop-os/cosmic/issues/264
